2025-05-16 01:32:55,911 INFO    MainThread:3795138 [wandb_init.py:setup_run_log_directory():662] Logging user logs to /sdf/home/c/carsmith/PILArNet-ML/3d_segment/wandb/run-20250516_013255-l1etwqcv/logs/debug.log
2025-05-16 01:32:55,911 INFO    MainThread:3795138 [wandb_init.py:setup_run_log_directory():663] Logging internal logs to /sdf/home/c/carsmith/PILArNet-ML/3d_segment/wandb/run-20250516_013255-l1etwqcv/logs/debug-internal.log
2025-05-16 01:32:55,911 INFO    MainThread:3795138 [wandb_init.py:init():781] calling init triggers
2025-05-16 01:32:55,911 INFO    MainThread:3795138 [wandb_init.py:init():786] wandb.init called with sweep_config: {}
config: {'epochs': 1, 'batch_size': 128, 'lr': 0.0001, '_wandb': {}}
2025-05-16 01:32:55,911 INFO    MainThread:3795138 [wandb_init.py:init():798] finishing previous run: c0bmaw1w
2025-05-16 01:32:56,619 INFO    MainThread:3795138 [wandb_init.py:init():809] starting backend
2025-05-16 01:32:56,619 INFO    MainThread:3795138 [wandb_init.py:init():813] sending inform_init request
2025-05-16 01:32:56,621 INFO    MainThread:3795138 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-05-16 01:32:56,621 INFO    MainThread:3795138 [wandb_init.py:init():823] backend started and connected
2025-05-16 01:32:56,625 INFO    MainThread:3795138 [wandb_run.py:_label_probe_notebook():1267] probe notebook
2025-05-16 01:32:56,625 INFO    MainThread:3795138 [wandb_run.py:_label_probe_notebook():1277] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2025-05-16 01:32:56,625 INFO    MainThread:3795138 [wandb_init.py:init():915] updated telemetry
2025-05-16 01:32:56,638 INFO    MainThread:3795138 [wandb_init.py:init():939] communicating run to backend with 90.0 second timeout
2025-05-16 01:32:57,061 INFO    MainThread:3795138 [wandb_init.py:init():1014] starting run threads in backend
2025-05-16 01:32:57,360 INFO    MainThread:3795138 [wandb_run.py:_console_start():2454] atexit reg
2025-05-16 01:32:57,360 INFO    MainThread:3795138 [wandb_run.py:_redirect():2306] redirect: wrap_raw
2025-05-16 01:32:57,360 INFO    MainThread:3795138 [wandb_run.py:_redirect():2371] Wrapping output streams.
2025-05-16 01:32:57,360 INFO    MainThread:3795138 [wandb_run.py:_redirect():2394] Redirects installed.
2025-05-16 01:32:57,361 INFO    MainThread:3795138 [wandb_init.py:init():1056] run started, returning control to user process
2025-05-16 01:33:27,371 INFO    MsgRouterThr:3795138 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 4 handles.
2025-05-16 01:33:28,085 ERROR   Thread-2 (_watch_pipe_fd):3795138 [redirect.py:_on_write():661] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/sdf/home/c/carsmith/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/sdf/home/c/carsmith/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2375, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/sdf/home/c/carsmith/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/sdf/home/c/carsmith/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/sdf/home/c/carsmith/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/sdf/home/c/carsmith/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/sdf/home/c/carsmith/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/sdf/home/c/carsmith/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/sdf/home/c/carsmith/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/sdf/home/c/carsmith/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/sdf/home/c/carsmith/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/sdf/home/c/carsmith/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
